package constantsCL

const (
	cl_khr_dx9_media_sharing                       = 1
	CL_INVALID_DX9_MEDIA_ADAPTER_KHR               = -1010
	CL_INVALID_DX9_MEDIA_SURFACE_KHR               = -1011
	CL_DX9_MEDIA_SURFACE_ALREADY_ACQUIRED_KHR      = -1012
	CL_DX9_MEDIA_SURFACE_NOT_ACQUIRED_KHR          = -1013
	CL_ADAPTER_D3D9_KHR                            = 0x2020
	CL_ADAPTER_D3D9EX_KHR                          = 0x2021
	CL_ADAPTER_DXVA_KHR                            = 0x2022
	CL_PREFERRED_DEVICES_FOR_DX9_MEDIA_ADAPTER_KHR = 0x2023
	CL_ALL_DEVICES_FOR_DX9_MEDIA_ADAPTER_KHR       = 0x2024
	CL_CONTEXT_ADAPTER_D3D9_KHR                    = 0x2025
	CL_CONTEXT_ADAPTER_D3D9EX_KHR                  = 0x2026
	CL_CONTEXT_ADAPTER_DXVA_KHR                    = 0x2027
	CL_MEM_DX9_MEDIA_ADAPTER_TYPE_KHR              = 0x2028
	CL_MEM_DX9_MEDIA_SURFACE_INFO_KHR              = 0x2029
	CL_IMAGE_DX9_MEDIA_PLANE_KHR                   = 0x202A
	CL_COMMAND_ACQUIRE_DX9_MEDIA_SURFACES_KHR      = 0x202B
	CL_COMMAND_RELEASE_DX9_MEDIA_SURFACES_KHR      = 0x202C
)
